### ISSUE TITLE
Add support of vue-router

### ISSUE THREAD

**Issue by davidyuk** [fengyuanchen/vue-countly#1]
For example, as in `vue-matomo` package: https://github.com/AmazingDreams/vue-matomo/blob/d2191af4075186b4f9f92cac6d2caa3da5835802/src/index.js#L38-L62

**Comment by fengyuanchen** [comment]
You can customize it by yourself as:

```js
router.afterEach((to, from) => {
  Vue.Countly.q.push(['add_event', {
    key: 'route', 
    segmentation: {
      from: from.path,
      to: to.path,
    },
  }]);
});
```
